---
title: 'Dimensionality Reduction and Cluster Annotation'
author: 'WD'
output:
  pdf_document:
    number_sections: yes
    keep_tex: yes
  html_document:
    df_print: paged
---

# Load packages and files

```{r echo=FALSE}
library("Seurat")
library("tidyverse")
library("dplyr")
library("ggplot2")
library("gridExtra")
library("SeuratDisk")
```

```{r include=FALSE}
denyer_wt <- LoadH5Seurat("../intermediate_files/denyer_wt_sctransform.h5seurat")

# OR
#denyer_wt <- LoadH5Seurat("../preprocessing/denyer_wt_lognormalized.h5seurat")
```

# Dimension reduction

## PCA

```{r}
denyer_wt <- RunPCA(denyer_wt, features = VariableFeatures(object=denyer_wt))
```

```{r}
VizDimLoadings(denyer_wt, dims = 1:4, reduction = "pca", combine=TRUE, nfeatures = 10)
```

```{r}
p1 <- DimHeatmap(denyer_wt, dims = 1:9, balanced = TRUE)
p1
```

```{r}
ElbowPlot(denyer_wt, ndims=40)
```

The curve flattens off around ~30 PCs, so I will work with that. 

```{r}
p2 <- DimPlot(denyer_wt, reduction = "pca")
p2
```

# Non-linear dimensionality reduction methods & clustering

```{r}
#KNN
set.seed(1234)
denyer_wt <- RunUMAP(denyer_wt, dims = 1:30, return.model = TRUE)
denyer_wt <- FindNeighbors(denyer_wt, dims=1:30)
denyer_wt <- FindClusters(denyer_wt, resolution = c(0.3, 0.5, 0.8, 1, 1.2))

DimPlot(denyer_wt, reduction="umap", group.by = "SCT_snn_res.1")

DimPlot(denyer_wt, reduction="umap") + scale_x_reverse()
```


```{r eval=FALSE, include=FALSE}
#idea for later: compare different clustering algorithms

for (num in c(1, 2, 3, 4)){
  denyer_wt <- FindClusters(denyer_wt, algorithm = num)
  assign(paste("wt_clustertest_", num, sep=""), DimPlot(denyer_wt, reduction = "umap"))
}

for (num in c(1, 2, 3, 4)){
  denyer_wt <- FindClusters(denyer_shr, algorithm = num)
  assign(paste("shr_clustertest_", num, sep=""), DimPlot(denyer_wt, reduction = "umap"))
}
```

# Finding differentially expressed features (cluster biomarkers)

```{r}
# find markers for every cluster compared to all remaining cells, report only the positive
# ones
denyer_wt <- SetIdent(denyer_wt, value ="SCT_snn_res.1")
wt_denyer_markers <- FindAllMarkers(denyer_wt, logfc.threshold = 0.5, min.pct=0.25, only.pos = TRUE)
```

```{r}
#Save objects for later

saveRDS(wt_denyer_markers, file = "../intermediate_files/wt_cluster_DEgenes.rds")
SaveH5Seurat(denyer_wt, filename = "../intermediate_files/denyer_wt_sctransform_clustered.h5seurat", overwrite=TRUE)

#SaveH5Seurat(denyer_wt, filename = "preprocessing/denyer_wt_lognormalized_clustered.h5seurat")
#SaveH5Seurat(denyer_shr, filename = "preprocessing/denyer_shr_lognormalized_clustered.h5seurat")

rm(denyer_wt)
```

