---
title: "Ligand-receptor interactions"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(PlantPhoneDB)
library(ComplexHeatmap)
library(tidyverse)
library(tradeSeq)
```

# Cell-cell communication

## Static

```{r}
identities = c(
  "Meristematic 1",
  "Atrichoblast 1",
  "Atrichoblast 2",
  "Trichoblast 1",
  "Trichoblast 2",
  "Meristematic 2",
  "Cortex 1",
  "Cortex 2", 
  "QC"
)
epidermal_lineage <- denyer[, (denyer@meta.data$Brady.annotation %in% identities)]
epidermal_lineage[["epidermal_lineage"]] <- Idents(epidermal_lineage)
```


```{r}
load("../data/LR_pair_ath.RDa")

Heat <-
  LRscore(
    epidermal_lineage@assays$SCT@data,
    LRdb = LR_pair,
    cluster = Idents(epidermal_lineage),
    min.pct = 0.1,
    iterations = 100,
    method = 'Average'
  )
```

BH-adjust p-values

```{r}
Heat$Qvalue <- (p.adjust(Heat$Pvalue, "fdr"))
phoneDB_top <- Heat[Heat$Qvalue < 0.01, ]
phoneDB_top <- phoneDB_top %>% filter(Ligands_cell != "QC" & Receptors_cell != "QC")
```

Filter interactions between cluster of the same cell type (!= autocrine), e.g. trichoblast 1 and 2 represent different developmental stages of the same cell and are therefore spatially not close. 

```{r}
# library(stringr)
# to_drop <- phoneDB_top %>%
#   mutate(Type = ifelse(Ligands_cell == Receptors_cell, "Autocrine", "Paracrine")) %>%
#   select(Ligands_cell, Receptors_cell, Type) %>%
#   rownames_to_column("rows") %>%
#   apply(MARGIN = 2, FUN = function(x){stringr::str_extract(x, pattern = "[:word:]+")}) %>%
#   as.data.frame() %>%
#   filter(Ligands_cell == Receptors_cell & Type == "Paracrine") %>%
#   pull(rows)
# 
# phoneDB_top <- phoneDB_top %>% filter(!rownames(phoneDB_top) %in% to_drop)
```

```{r}
interaction_count <- phoneDB_top %>%
  group_by(Ligands_cell, Receptors_cell) %>%
  summarise(Number = n(), .groups = 'drop')
```

```{r}
options(repr.plot.width = 6, repr.plot.height = 5)
heatmap_count(
  interaction_count,
  text_size = 7.82,
  number_size = 3,
  decimal = 4,
  title = ""
)
```

```{r}
Top20 <- phoneDB_top %>%
    arrange(desc(Score)) %>%
    select(LR_pair) %>%
    unique() %>%
    head(50) %>%
    inner_join(Heat) %>%
    select(LR_pair,Cell_pair,Score) %>%
    spread(.,Cell_pair,Score) %>%
    replace(is.na(.), 0)
```

```{r}
rownames(Top20) <- Top20$LR_pair
Top20 <- Top20[,-1]
Top20 <- t(Top20)
```

```{r}
cells <- rownames(Top20)
Top20 <- apply(Top20,2,function(x){x/max(x)})
rownames(Top20) <- cells
```

```{r}
annot_sender <-
  sapply(rownames(Top20), function(x) {
    str_split(x, pattern = "->")
  }) %>% lapply(function(x) {
    x[1]
  }) %>% unlist()

annot_receiver <-
  sapply(rownames(Top20), function(x) {
    str_split(x, pattern = "->")
  }) %>% lapply(function(x) {
    x[2]
  }) %>% unlist()

annot_ligand <-
  sapply(colnames(Top20), function(x) {
    str_split(x, pattern = "->")
  }) %>% lapply(function(x) {
    x[1]
  }) %>% unlist()

annot_receptor <-
  sapply(colnames(Top20), function(x) {
    str_split(x, pattern = "->")
  }) %>% lapply(function(x) {
    x[2]
  }) %>% unlist()

ht <- Heatmap(
  Top20,
  column_dend_reorder = T,
  cluster_columns = T,
  show_column_names = FALSE,
  show_row_names = FALSE,
  left_annotation = HeatmapAnnotation(#sender = annot_sender,
    receiver = annot_receiver, which = "row"),
  top_annotation = HeatmapAnnotation(#ligand = annot_ligand,
    receptor = annot_receptor, which = "col"),
  column_km = 5
)

ht
```

Extract clusters

```{r}
ht = draw(ht)
dend = column_dend(ht)
lst = column_order(ht)

for (i in 1:length(lst)){
  if (i == 1){
  clu <- t(t(colnames(Top20[lst[[i]],])))
  out <- cbind(clu, i)
  colnames(out) <- c("GeneID", "Cluster")
  } else {
    clu <- t(t(colnames(Top20[lst[[i]],])))
    clu <- cbind(clu, i)
    out <- rbind(out, clu)}}

out <- out %>% 
  as.data.frame() %>%
  mutate(Cluster = as.numeric(Cluster))

c <- sapply(out$GeneID,
            function(x) {
              stringr::str_extract_all(x, pattern = "AT[:digit:]G[:digit:]{5}")
            }) %>% do.call(rbind.data.frame, .)
colnames(c) <- c("lig", "rec")

signal_genemodules <- data.frame(cluster = rep(out$Cluster, each = 2), gene = with(c, ggplot2:::interleave(lig,rec))) %>%
  group_by(cluster) %>% 
  distinct(gene) %>% 
  ungroup()
```

No enrichment :(

## Dynamic

```{r}
# get pseudotime smoother per gene
yhatSmooth <-
  predictSmooth(
    epidermal_tradeseq,
    gene = pseudo.signif.genes,
    nPoints = 30,
    tidy = TRUE
  ) %>%
  mutate(lineage = paste0("Lineage", lineage)) %>%
  group_by(lineage) %>%
  group_split() %>%
  lapply(function(x) {
    pivot_wider(dplyr::select(x,-c("lineage")),
                names_from = "time",
                values_from = "yhat")
  })

lineages <- slingLineages(epidermal_sds)

# make unique names for interacting LR pairs
tmp <- phoneDB_top %>%
  arrange(desc(Score)) %>%
  filter(
    Ligands_cell %in% c(
      "Cortex 1",
      "Cortex 2",
      "Atrichoblast 1",
      "Atrichoblast 2",
      "Trichoblast 1",
      "Trichoblast 2"
    ) &
      Receptors_cell %in% c(
        "Cortex 1",
        "Cortex 2",
        "Atrichoblast 1",
        "Atrichoblast 2",
        "Trichoblast 1",
        "Trichoblast 2"
      )
  ) %>% filter(Ligands_cell != Receptors_cell) %>%
  mutate(LR_pair  = make.names(names = LR_pair, unique = TRUE))

# add lineage information for ligands and receptors
for (line in names(lineages)) {
  new_lig <-
    replace(tmp$Ligands_cell,
            which(tmp$Ligands_cell %in% lineages[[line]]),
            line)
  new_rec <-
    replace(tmp$Receptors_cell,
            which(tmp$Receptors_cell %in% lineages[[line]]),
            line)
  tmp$Ligands_cell <- new_lig
  tmp$Receptors_cell <- new_rec
}

tmp <-
  distinct(tmp,
           Ligands,
           Receptors,
           Ligands_cell,
           Receptors_cell,
           .keep_all = TRUE)

# first do for ligand data
lig <- tmp %>%
  rename("gene" = "Ligands") %>%
  group_by(Ligands_cell) %>% group_split() %>%
  lapply(function(x) {
    dplyr::select(x,
           -c("Receptors", "Cell_pair"))
  })


# do same for receptor data
rec <- tmp %>%
  rename("gene" = "Receptors") %>%
  group_by(Receptors_cell) %>% group_split() %>%
  lapply(function(x) {
    dplyr::select(x,
           -c("Ligands", "Cell_pair"))
  })

# combine lineage information for ligand/receptor with tradeseq pseudotime smoother
ligand_time <- list()
receptor_time <- list()
for (i in c(1, 2, 4)) {
  new_lig <- merge(yhatSmooth[[i]], lig[[i]], by = "gene")
  new_rec <- merge(yhatSmooth[[i]], rec[[i]], by = "gene")
  names(new_lig) <- c("gene", 1:30, "Ligands_cell", "Receptors_cell", "pair")
  names(new_rec) <- c("gene", 1:30, "Ligands_cell", "Receptors_cell", "pair")
  ligand_time[[i]] <- new_lig
  receptor_time[[i]] <- new_rec
}

ligand_time <- do.call(rbind, ligand_time)
receptor_time <- do.call(rbind, receptor_time)

# only keep if there is information on both members of interacting pair
common <- intersect(ligand_time$pair, receptor_time$pair)
ligand_time <-
  ligand_time[ligand_time$pair %in% common,]
receptor_time <-
  receptor_time[receptor_time$pair %in% common,]
```

### Heatmap 

```{r}
# calculate average expression for interacting pairs
pairs_heatmapdata <- (receptor_time[, 2:31] + ligand_time[match(ligand_time$pair, receptor_time$pair), 2:31]) / 2
rownames(pairs_heatmapdata) <- receptor_time$pair

row_meta <- data.frame(label = receptor_time$Receptors_cell, row.names = receptor_time$pair)

signalheatmap <- pheatmap::pheatmap(t(scale(t(pairs_heatmapdata))), cluster_cols = F, show_rownames = F, clustering_method = "ward.D", cutree_row = 6 #, annotation_row = row_meta
                                    )
```


```{r}
signal_modules <- data.frame(cluster = as.factor(cutree(signalheatmap$tree_row,  k = 6)))

c <- sapply(rownames(signal_modules), 
            function(x){stringr::str_extract_all(x, pattern = "AT[:digit:]G[:digit:]{5}")}) %>% do.call(rbind.data.frame, .)
colnames(c) <- c("lig", "rec")

signal_genemodules <- data.frame(cluster = rep(signal_modules$cluster, each = 2), gene = with(c, ggplot2:::interleave(lig,rec))) %>%
  group_by(cluster) %>% 
  distinct(gene) %>% 
  ungroup()
```

```{r}
assayed.genes <- rownames(denyer)[rownames(denyer) %in% c(LR_pair$Ligands, LR_pair$Receptors)]
countbias <- rowMeans(denyer) %>% data.frame(row.names = rownames(denyer))
countbias <- countbias[rownames(countbias) %in% assayed.genes,]

patGO <- function(ClusterGenes, countbias, getgo, pval) {
  results <- list()
  for (c in 1:length(unique(ClusterGenes$cluster))) {
    print(paste0("Calculating cluster", c))
    de.genes <- ClusterGenes %>% filter(cluster == c) %>% pull(gene)
    gene.vector <- as.integer(assayed.genes %in% de.genes)
    names(gene.vector) <- assayed.genes
    pwf = nullp(gene.vector,
                "Arabidopsis",
                bias.data = countbias,
                plot.fit = F)
    go.nobias <-
      suppressWarnings(goseq(pwf, gene2cat = getgo, method = "Hypergeometric"))
    go.nobias$over_represented_qvalue <-
      p.adjust(go.nobias$over_represented_pvalue, method = "BH")
    results[[c]] <- go.nobias
    print(paste0("Added cluster", c))
  }
  results <- enframe(results) %>%
    unnest() %>% filter(over_represented_qvalue < pval)
  results
}
```


```{r}
signalGO <- patGO(signal_genemodules, countbias = countbias, getgo = groups_bp, pval = 1)
```

No enrichment :/

```{r fig.width=12, fig.height=8}
c <-
  signalGO %>% dplyr::select(name, category, term, over_represented_qvalue) %>% 
  distinct(name, term, .keep_all = T) %>%
  mutate(over_represented_qvalue = signif(over_represented_qvalue, digits = 2)) %>%
  mutate(text = paste(term, paste0("(", over_represented_qvalue, ")"))) %>% 
  mutate(fontsize = 9) %>%
  split(signalGO$name) %>%
  lapply(function(x){data.frame(text = x$text, fontsize = x$fontsize)})

d <- merge(tmp, signal_modules, by.x = 'LR_pair', by.y = 0) %>% 
  split(.$cluster) %>% 
  lapply(function(x){x %>% arrange(desc(Score)) %>% 
      head(6) %>% 
      mutate(text = paste(Ligands, Receptors, Cell_pair)) %>%
      mutate(fontsize = 6) %>% dplyr::select(text, fontsize) %>% arrange(text)})
  
pdf(file = "../figures/signalgenes_heatmap.pdf", width = 20, height = 6.5)
p <- Heatmap(t(scale(t(pairs_heatmapdata))),
        column_dend_reorder = FALSE,
        cluster_columns = FALSE, 
        show_column_names = FALSE, 
        row_split = signal_modules,
        show_row_names = FALSE,
        border = TRUE, 
        right_annotation = rowAnnotation(
          textbox = anno_textbox(signal_modules$cluster, d, word_wrap = TRUE, add_new_line = TRUE)), 
        width = unit(15, "cm"),
        row_title = NULL, 
        cluster_row_slices = FALSE
  )
draw(p)
dev.off()
```
